### ISSUE TITLE
Only unpack product-info.json to check version

### ISSUE THREAD

**Issue by func0der** [diademiemi/ansible_collection_diademiemi.jetbrains#1]
Instead of unpacking the whole piece of software, we could only unpack the json file you need for the version check.
Though we did not get around the fact that we downloaded the whole release before, it would prevent the very long and most of the time unnecessary process of unpacking it completely.

Here is the line I am referring to: https://github.com/diademiemi/ansible_collection_diademiemi.jetbrains/blob/b95d12f29f4624a710faaeef6fb82db853339f28/roles/common/tasks/setup/always.yml#L40

What do you think about this idea?

**Comment by x86-39** [comment]
That's a good idea, I'll look into how this could be reliably done for every archive! It might also finally fix CI if it takes less long...

**Comment by func0der** [comment]
I created a PR. Maybe this is already all that is needed. :)

**Comment by x86-39** [comment]
PR merged! Thank you!
